/* ============================================================
   剧本 · 星见丘  ——  10 章 / 7 结局
   节点类型：
     chapter  章节卡   {title, sub}
     bg       换背景   {cls, fx}          cls 见 index.html 的 .bg-* / url 类
     say      对话     {who:'me'|'ynn'|'narr'|'其他', text}
     choice   选项     {options:[{text, aff, to}]}
     label    跳转标记 {name}
     jump     跳转到   {to}
     check    条件分支 {branches:[{min, to}]}   按好感度从高到低写
     end      结局     {kind, title, text, affText}
   text 里的 {name} 会替换成男主名字，\n 换行
   ============================================================ */
const SCRIPT = [

/* ============================================================
   序章
   ============================================================ */
{type:'chapter', title:'序 章', sub:'四 月 · 樱 色 的 坡 道'},
{type:'bg', cls:'bg-cherry', fx:''},
{type:'say', who:'narr', text:'四月，樱花开满了星见丘的坡道。\n花瓣被风卷起来，像是有人把整片天空撕成了碎片。'},
{type:'say', who:'narr', text:'我——刚转学来的二年级生，拎着一只还带着标签的书包，站在校门口发呆。'},
{type:'say', who:'me',   text:'（这就是我接下来两年要待的地方啊……）'},
{type:'say', who:'me',   text:'（没有认识的人，没有熟悉的路，什么都没有。）'},
{type:'say', who:'narr', text:'校舍比地图上画的还要大。走廊弯弯绕绕，像是故意和新生作对。'},
{type:'say', who:'me',   text:'……我迷路了。'},
{type:'say', who:'narr', text:'在第三次经过同一个消防栓之后，我终于承认了这个事实。'},
{type:'say', who:'me',   text:'（离上课还有五分钟。教室是二年B组……在几楼来着？）'},
{type:'say', who:'narr', text:'就在我准备原地放弃的时候，走廊尽头传来一个声音。'},
{type:'say', who:'ynn',  text:'你在找二年B组吧。'},
{type:'say', who:'narr', text:'靠着窗边站着一个女生。逆光里看不清表情，只看见她抱着很厚的一本书。'},
{type:'say', who:'ynn',  text:'从刚才开始，你已经在楼梯口转了三圈。'},
{type:'say', who:'me',   text:'你、你一直在看？'},
{type:'say', who:'ynn',  text:'我只是刚好在等人。顺便看了三圈。'},
{type:'say', who:'me',   text:'……被你看见这种样子，真是。'},
{type:'say', who:'ynn',  text:'没什么。迷路很正常。'},
{type:'say', who:'ynn',  text:'二年B组在三楼东侧。直走，右拐，经过两个教室，左手边。'},
{type:'say', who:'narr', text:'她的语气没什么起伏，句子却像刻在纸上的标尺一样准确。'},
{type:'say', who:'me',   text:'谢……'},
{type:'say', who:'ynn',  text:'还有两分钟。跑的话，来得及。'},
{type:'say', who:'me',   text:'那你呢？不用上课吗？'},
{type:'say', who:'ynn',  text:'我在等人。'},
{type:'say', who:'me',   text:'等谁？'},
{type:'say', who:'ynn',  text:'……一个不会来的人。'},
{type:'say', who:'narr', text:'说完，她低下头重新翻开书——封面上写着两个字：《海》。'},
{type:'say', who:'narr', text:'我记住了她的侧脸，然后真的跑了起来。'},

/* ============================================================
   第一章
   ============================================================ */
{type:'chapter', title:'第 一 章', sub:'走 廊 尽 头 的 她'},
{type:'bg', cls:'bg-corridor', fx:''},
{type:'say', who:'narr', text:'结果当然没赶上。第一节课，我在讲台边站了十分钟。'},
{type:'say', who:'narr', text:'班主任让我自我介绍的时候，我说了三个字就把舌头咬到了。\n全班笑得很整齐。'},
{type:'say', who:'narr', text:'午休，我在自动贩卖机前排队，又看见了那个抱着书的女生。'},
{type:'say', who:'ynn',  text:'……迷路的人。'},
{type:'say', who:'me',   text:'我叫{name}。不叫迷路的人。'},
{type:'say', who:'ynn',  text:'ynn。请多指教，迷路的人。'},
{type:'say', who:'me',   text:'（完全没打算改口。）'},
{type:'say', who:'narr', text:'她抱着书的样子有点特别——不是那种抱课本的随手一夹，\n而是双手掌心托着，像怕它掉。'},
{type:'say', who:'me',   text:'那本《海》，很好看吗？'},
{type:'say', who:'ynn',  text:'……'},
{type:'say', who:'ynn',  text:'不是好看不好看的问题。'},
{type:'say', who:'ynn',  text:'是最后一页的问题。'},
{type:'say', who:'me',   text:'最后一页怎么了？'},
{type:'say', who:'narr', text:'她把书往怀里收了收。'},
{type:'say', who:'ynn',  text:'如果你想知道，自己看。'},
{type:'say', who:'ynn',  text:'……但不是现在。'},
{type:'choice', options:[
  {text:'「昨天多谢了，真的帮了大忙。」', aff:1, to:'ch1_a'},
  {text:'「我请你喝瓶牛奶，当谢礼。」', aff:3, to:'ch1_b'},
  {text:'「你该不会天天守在这儿看新生出丑吧？」', aff:-1, to:'ch1_c'}
]},

{type:'label', name:'ch1_a'},
{type:'say', who:'me',   text:'「昨天多谢了，真的帮了大忙。」'},
{type:'say', who:'ynn',  text:'……没什么。'},
{type:'say', who:'narr', text:'她的耳朵好像红了一下。不过也可能是阳光的关系。'},
{type:'say', who:'ynn',  text:'我只是不喜欢看见有人在走廊上原地打转。'},
{type:'say', who:'me',   text:'这算哪门子的理由啊。'},
{type:'say', who:'ynn',  text:'很好的理由。'},
{type:'say', who:'narr', text:'她把书合上，抱着往教室走。走了两步，又停下。'},
{type:'say', who:'ynn',  text:'{name}。'},
{type:'say', who:'me',   text:'嗯？'},
{type:'say', who:'ynn',  text:'下午第二节课要换教室。别又迷路。'},
{type:'say', who:'narr', text:'她说完就走了。我在原地站了几秒，忽然觉得这个学校也不错。'},
{type:'jump', to:'ch1_end'},

{type:'label', name:'ch1_b'},
{type:'say', who:'me',   text:'「我请你喝瓶牛奶，当谢礼。」'},
{type:'say', who:'narr', text:'她看了我一眼，看了看贩卖机，又看了我一眼。'},
{type:'say', who:'ynn',  text:'……草莓的。'},
{type:'say', who:'me',   text:'诶？'},
{type:'say', who:'ynn',  text:'草莓味。三号按钮。'},
{type:'say', who:'narr', text:'我买了瓶草莓牛奶递过去。她双手接住，像捧着一件很重要的东西。'},
{type:'say', who:'ynn',  text:'谢谢。'},
{type:'say', who:'narr', text:'她把牛奶贴在脸颊上，眯了眯眼。'},
{type:'say', who:'ynn',  text:'……凉的，很舒服。'},
{type:'say', who:'me',   text:'你笑了。'},
{type:'say', who:'ynn',  text:'没有。'},
{type:'say', who:'me',   text:'笑了。'},
{type:'say', who:'ynn',  text:'……没有。'},
{type:'say', who:'narr', text:'她转身就走，比昨天走得快。但我发誓，她嘴角还是翘着的。'},
{type:'say', who:'narr', text:'第二天早上，我桌洞里多了一瓶空的草莓牛奶瓶。\n瓶身上用铅笔写了一个很小的「还」。'},
{type:'jump', to:'ch1_end'},

{type:'label', name:'ch1_c'},
{type:'say', who:'me',   text:'「你该不会天天守在这儿看新生出丑吧？」'},
{type:'say', who:'narr', text:'空气安静了三秒。'},
{type:'say', who:'ynn',  text:'……原来你是这么想的。'},
{type:'say', who:'me',   text:'呃，我开玩笑的。'},
{type:'say', who:'ynn',  text:'我知道。只是玩笑不好笑。'},
{type:'say', who:'narr', text:'她把书抱得更紧了一点，转身走了。'},
{type:'say', who:'narr', text:'我站在原地，看着她的背影，忽然觉得自己刚才很蠢。'},
{type:'say', who:'me',   text:'（下次……还是好好说话吧。）'},
{type:'jump', to:'ch1_end'},

{type:'label', name:'ch1_end'},
{type:'bg', cls:'bg-sunset', fx:''},
{type:'say', who:'narr', text:'那天下午，我在楼梯口又遇到了她。她什么都没说，只抬了抬下巴，指了个方向。'},
{type:'say', who:'me',   text:'……谢了。'},
{type:'say', who:'ynn',  text:'嗯。'},
{type:'say', who:'narr', text:'她走在我前面半步，像是怕我跟丢。夕阳把两个人的影子拉得很长。'},
{type:'say', who:'me',   text:'（总觉得……这个人，好像不太会跟人说话。）'},
{type:'say', who:'me',   text:'（但她说的话，每一句都很有用。）'},

/* ============================================================
   第二章
   ============================================================ */
{type:'chapter', title:'第 二 章', sub:'雨 · 与 一 把 伞'},
{type:'bg', cls:'bg-rain', fx:'rain'},
{type:'say', who:'narr', text:'梅雨季来得毫无预告。放学时，天已经黑得像晚上七点。'},
{type:'say', who:'narr', text:'我站在玄关，看着外面的雨帘，感叹自己没有带伞这件事。'},
{type:'say', who:'me',   text:'（走回去大概二十分钟……冲吧。）'},
{type:'say', who:'ynn',  text:'你要淋雨回去？'},
{type:'say', who:'narr', text:'ynn站在我旁边，手里是一把透明的伞。伞柄上挂着一只很旧的小熊挂件。'},
{type:'say', who:'me',   text:'你家不是反方向吗？'},
{type:'say', who:'ynn',  text:'绕一圈而已。'},
{type:'say', who:'ynn',  text:'……一起走吧。'},
{type:'say', who:'narr', text:'那只小熊挂件的毛已经秃了一半，颜色也褪成了很浅的粉。'},
{type:'say', who:'narr', text:'不知道被握了多少年。'},
{type:'choice', options:[
  {text:'「伞往你那边多挪一点，你肩膀都湿了。」', aff:3, to:'ch2_a'},
  {text:'「那一起跑吧，反正都湿透了。」', aff:1, to:'ch2_b'},
  {text:'「你先走吧，我自己能回去。」', aff:-2, to:'ch2_c'}
]},

{type:'label', name:'ch2_a'},
{type:'say', who:'me',   text:'「伞往你那边多挪一点，你肩膀都湿了。」'},
{type:'say', who:'ynn',  text:'……那你呢。'},
{type:'say', who:'me',   text:'我皮实。'},
{type:'say', who:'narr', text:'她沉默了一会儿，把伞又往我这边推了回来。'},
{type:'say', who:'ynn',  text:'两个人一起湿，不如一个人湿。这叫效率。'},
{type:'say', who:'me',   text:'这是哪门子的效率啊。'},
{type:'say', who:'ynn',  text:'……我的效率。'},
{type:'say', who:'narr', text:'结果那把伞在两个人之间来回推了好几次，最后谁都没淋到多少雨。'},
{type:'say', who:'narr', text:'倒是肩膀，一直贴着肩膀。'},
{type:'say', who:'narr', text:'走到她家路口的时候，她停下脚步。'},
{type:'say', who:'ynn',  text:'……你刚才，为什么要往我这边推。'},
{type:'say', who:'me',   text:'因为你肩膀湿了啊。'},
{type:'say', who:'ynn',  text:'……'},
{type:'say', who:'ynn',  text:'嗯。'},
{type:'say', who:'narr', text:'她转身走进雨里，走了三步，忽然又回头。'},
{type:'say', who:'ynn',  text:'{name}。'},
{type:'say', who:'ynn',  text:'……明天也，带伞。'},
{type:'say', who:'narr', text:'说完她就跑了，透明伞在雨里晃了一下。'},
{type:'jump', to:'ch2_end'},

{type:'label', name:'ch2_b'},
{type:'say', who:'me',   text:'「那一起跑吧，反正都湿透了。」'},
{type:'say', who:'ynn',  text:'……幼稚。'},
{type:'say', who:'narr', text:'但她还是把伞收了一半，跟上了我的脚步。'},
{type:'say', who:'narr', text:'水花在脚下溅开，两个人的笑声混进了雨声里。'},
{type:'say', who:'ynn',  text:'{name}，你跑得真慢。'},
{type:'say', who:'me',   text:'你刚才明明说不跑的！'},
{type:'say', who:'ynn',  text:'……我没说。'},
{type:'say', who:'narr', text:'那天回家我感冒了。第二天来学校，桌洞里多了一包感冒药。'},
{type:'say', who:'narr', text:'没有署名。'},
{type:'say', who:'narr', text:'药盒背面用很小的字写着：「一次一粒。别空腹。」'},
{type:'narr_note', text:''},
{type:'say', who:'me',   text:'（这字迹……）'},
{type:'say', who:'narr', text:'我抬起头，靠窗的那个位置上空着。'},
{type:'say', who:'narr', text:'下午她才来。进门的时候看了我一眼，什么都没说。'},
{type:'jump', to:'ch2_end'},

{type:'label', name:'ch2_c'},
{type:'say', who:'me',   text:'「你先走吧，我自己能回去。」'},
{type:'say', who:'ynn',  text:'……好。'},
{type:'say', who:'narr', text:'她走了两步，又回头看了一次。'},
{type:'say', who:'narr', text:'我把书包顶在头上，冲进雨里。'},
{type:'say', who:'narr', text:'跑到一半，我忽然觉得，刚才那句话好像说错了。'},
{type:'say', who:'narr', text:'第二天，她的桌洞里有一把我没见过的伞。\n新的，标签还没撕。'},
{type:'say', who:'me',   text:'（……那个标签，是我上次买牛奶的便利店。）'},
{type:'jump', to:'ch2_end'},

{type:'label', name:'ch2_end'},
{type:'bg', cls:'bg-rain', fx:'rain'},
{type:'say', who:'narr', text:'那条回家的路，因为多了一把伞，好像变短了。'},
{type:'say', who:'ynn',  text:'明天……带伞。天气预报说还要下。'},
{type:'say', who:'me',   text:'知道了，长官。'},
{type:'say', who:'ynn',  text:'……谁是你的长官。'},
{type:'say', who:'narr', text:'她把透明伞收好，小熊挂件晃了晃。'},

/* ============================================================
   第三章
   ============================================================ */
{type:'chapter', title:'第 三 章', sub:'图 书 馆 的 午 后'},
{type:'bg', cls:'bg-library', fx:''},
{type:'say', who:'narr', text:'期中考前两周。我抱着三本参考书，在图书馆的角落找到了她。'},
{type:'say', who:'narr', text:'她坐在靠窗的位置，面前摊着笔记本，手里却在画着什么。'},
{type:'say', who:'me',   text:'你也在复习？'},
{type:'say', who:'ynn',  text:'嗯。'},
{type:'say', who:'narr', text:'她把笔记本往前挪了挪，挡住我的视线。太可疑了。'},
{type:'say', who:'narr', text:'阳光落在她手背上。铅笔在纸上沙沙地响。'},
{type:'say', who:'narr', text:'我没有走。把书放在她对面，坐下。'},
{type:'say', who:'narr', text:'她画了大概二十分钟，我看了二十分钟。'},
{type:'choice', options:[
  {text:'「画得真好。是什么？」（认真地夸她）', aff:3, to:'ch3_a'},
  {text:'「让我看看你的笔记本？」（伸手去拿）', aff:-3, to:'ch3_b'},
  {text:'什么都不问，坐下来安静地陪她', aff:2, to:'ch3_c'}
]},

{type:'label', name:'ch3_a'},
{type:'say', who:'me',   text:'「画得真好。是什么？」'},
{type:'say', who:'ynn',  text:'……你不该看到的。'},
{type:'say', who:'me',   text:'是星空？'},
{type:'say', who:'narr', text:'画纸上是一片深蓝。一颗一颗的星星，全是铅笔点出来的，密密麻麻。'},
{type:'say', who:'ynn',  text:'……星见丘。这个城市，晚上看不见星星。所以只能画。'},
{type:'say', who:'me',   text:'为什么是星星？'},
{type:'say', who:'ynn',  text:'因为我小时候，在奶奶家看过一次。一整条银河，像撒下来的糖。'},
{type:'say', who:'ynn',  text:'……我从那天开始，就想再看一次。'},
{type:'say', who:'narr', text:'她像是后悔说了这么多，把本子合上。'},
{type:'say', who:'ynn',  text:'别多想。只是随便画画。'},
{type:'say', who:'me',   text:'我没多想。我只是觉得……很好看。'},
{type:'say', who:'narr', text:'她的笔停了一下。'},
{type:'say', who:'ynn',  text:'……嗯。'},
{type:'say', who:'narr', text:'那天她走的时候，把笔记本留在了桌上。'},
{type:'say', who:'narr', text:'不是忘了。是故意放在那里的。'},
{type:'say', who:'me',   text:'（……她画了一百四十七颗星。）'},
{type:'say', who:'me',   text:'（最右边那颗，还没画。）'},
{type:'jump', to:'ch3_end'},

{type:'label', name:'ch3_b'},
{type:'say', who:'me',   text:'「让我看看你的笔记本？」'},
{type:'say', who:'narr', text:'她按住了本子。'},
{type:'say', who:'ynn',  text:'不行。'},
{type:'say', who:'me',   text:'只是看一眼——'},
{type:'say', who:'ynn',  text:'{name}。'},
{type:'say', who:'narr', text:'她抬起头，眼睛很认真。'},
{type:'say', who:'ynn',  text:'我不想给你看。为什么你听不见呢。'},
{type:'say', who:'narr', text:'我伸出去的手僵在半空。'},
{type:'say', who:'narr', text:'图书馆很安静，安静得能听见自己刚才的失礼。'},
{type:'say', who:'narr', text:'她抱着笔记本走了。走之前，把椅子推回了原位。'},
{type:'say', who:'narr', text:'连椅子都摆得很正。像是要把刚才那段也一起摆正。'},
{type:'jump', to:'ch3_end'},

{type:'label', name:'ch3_c'},
{type:'say', who:'narr', text:'我什么也没问，把书包放下，坐在她对面。'},
{type:'say', who:'narr', text:'翻书，写题，偶尔抬头——她还在画她的星空。'},
{type:'say', who:'narr', text:'一个小时过去，她一句话没说。'},
{type:'say', who:'narr', text:'离开的时候，她忽然开口。'},
{type:'say', who:'ynn',  text:'……你不问吗？'},
{type:'say', who:'me',   text:'如果你想说的话，会说。'},
{type:'say', who:'narr', text:'她看了我很久，久到我以为她要说什么了。'},
{type:'say', who:'ynn',  text:'……你这个人，还不错。'},
{type:'say', who:'narr', text:'那是她第二次这么说我。'},
{type:'jump', to:'ch3_end'},

{type:'label', name:'ch3_end'},
{type:'say', who:'narr', text:'从那天起，图书馆靠窗的位置，成了两个人的座位。'},
{type:'say', who:'narr', text:'她从来不说「你来啦」。但我一到，她就会把旁边的椅子，\n用脚尖轻轻推出来一点。'},
{type:'say', who:'me',   text:'（大概推了三厘米。）'},
{type:'say', who:'me',   text:'（但我每次都看见了。）'},

/* ============================================================
   第四章
   ============================================================ */
{type:'chapter', title:'第 四 章', sub:'文 化 祭 的 星 空'},
{type:'bg', cls:'bg-sunset', fx:''},
{type:'say', who:'narr', text:'文化祭前夜，班里决定做一台星空投影。'},
{type:'say', who:'narr', text:'原因很简单——有人说，「反正我们班有个会画星星的人」。'},
{type:'say', who:'narr', text:'于是那天晚上，美术教室里只剩下两个人。'},
{type:'say', who:'ynn',  text:'这里，再补一点。不然北极星会掉下来。'},
{type:'say', who:'me',   text:'星星还能掉下来吗？'},
{type:'say', who:'ynn',  text:'能。只要画错了，就会。'},
{type:'say', who:'narr', text:'她踮起脚，在天花板的投影纸上补了一个小小的点。'},
{type:'say', who:'ynn',  text:'好了。'},
{type:'say', who:'narr', text:'灯关掉的一瞬间，整个教室变成了一片夜。'},
{type:'say', who:'me',   text:'哇……'},
{type:'say', who:'ynn',  text:'……还行吧。'},
{type:'say', who:'narr', text:'她坐在课桌上，仰着头。星光落在她的眼睛里。'},
{type:'say', who:'me',   text:'（原来她坐在课桌上的时候，脚尖碰不到地。）'},
{type:'say', who:'me',   text:'（这件事，我不知道为什么记住了。）'},
{type:'choice', options:[
  {text:'「明天，一起去天台看真正的星星吧。」', aff:4, to:'ch4_a'},
  {text:'「你看起来很开心。」', aff:2, to:'ch4_b'},
  {text:'「先回去睡吧，明天还要早起。」', aff:-2, to:'ch4_c'}
]},

{type:'label', name:'ch4_a'},
{type:'say', who:'me',   text:'「明天，文化祭结束以后，一起去天台吧。」'},
{type:'say', who:'ynn',  text:'天台？'},
{type:'say', who:'me',   text:'我给你看真正的星星。虽然这个城市看不到什么。'},
{type:'say', who:'ynn',  text:'……看不到的星星，要看什么？'},
{type:'say', who:'me',   text:'看你画的那一片。'},
{type:'say', who:'me',   text:'这样，说不定就看见了。'},
{type:'say', who:'narr', text:'她安静了很久。久到我以为自己说错了话。'},
{type:'say', who:'ynn',  text:'……好。'},
{type:'say', who:'ynn',  text:'七点。不要迟到。'},
{type:'say', who:'narr', text:'那是她第一次，答应我的邀请。'},
{type:'say', who:'narr', text:'走出教室的时候，她走得很慢。'},
{type:'say', who:'narr', text:'慢到我不得不也放慢脚步。'},
{type:'jump', to:'ch4_end'},

{type:'label', name:'ch4_b'},
{type:'say', who:'me',   text:'「你看起来很开心。」'},
{type:'say', who:'ynn',  text:'没有。'},
{type:'say', who:'me',   text:'有。嘴角。'},
{type:'say', who:'ynn',  text:'……那是画歪了。'},
{type:'say', who:'me',   text:'画歪了会笑吗？'},
{type:'say', who:'ynn',  text:'会。'},
{type:'say', who:'ynn',  text:'……因为很开心。'},
{type:'say', who:'narr', text:'她小声说完最后四个字，把脸埋进膝盖里。'},
{type:'say', who:'narr', text:'头顶的星空还在转。她在里面待了很久。'},
{type:'jump', to:'ch4_end'},

{type:'label', name:'ch4_c'},
{type:'say', who:'me',   text:'「先回去睡吧，明天还要早起。」'},
{type:'say', who:'ynn',  text:'……嗯。'},
{type:'say', who:'narr', text:'她站起来，把灯打开。教室里的星空一下子消失了。'},
{type:'say', who:'narr', text:'她收拾东西的动作很轻，像是怕吵醒什么。'},
{type:'say', who:'ynn',  text:'晚安。'},
{type:'say', who:'narr', text:'走到门口，她停了一下。'},
{type:'say', who:'ynn',  text:'{name}。'},
{type:'say', who:'me',   text:'嗯？'},
{type:'say', who:'ynn',  text:'……没事。晚安。'},
{type:'say', who:'narr', text:'门关上之后，投影纸还挂在那里。'},
{type:'say', who:'narr', text:'我忽然觉得，刚才那句话应该收回来。'},
{type:'jump', to:'ch4_end'},

{type:'label', name:'ch4_end'},
{type:'bg', cls:'bg-night', fx:''},
{type:'say', who:'narr', text:'那一夜，我翻来覆去。窗外真的看不见星星。'},
{type:'say', who:'narr', text:'那一夜，我翻来覆去。窗外真的看不见星星。'},
{type:'jump', to:'ch5'},

{type:'label', name:'ch5'},
{type:'chapter', title:'第 五 章', sub:'海 边 的 风'},
{type:'bg', cls:'bg-sea', fx:''},
{type:'say', who:'narr', text:'周末。我们坐了一个小时的巴士，去看海。'},
{type:'say', who:'narr', text:'车票是我买的，路上她一直看着窗外，没怎么说话。'},
{type:'say', who:'narr', text:'她说她想找一样东西。具体是什么，她没说。'},
{type:'say', who:'me',   text:'（一个女生，约一个刚认识不久的人，去看海。这事儿本身就挺奇怪的。）'},
{type:'say', who:'me',   text:'（可我居然真的来了。）'},
{type:'say', who:'narr', text:'巴士在一个没有名字的站停下。下车就是海。'},
{type:'say', who:'ynn',  text:'……到了。'},
{type:'say', who:'ynn',  text:'原来还是很远。地图上看着没那么远。'},
{type:'say', who:'me',   text:'你以前来过吗？'},
{type:'say', who:'ynn',  text:'没有。'},
{type:'say', who:'ynn',  text:'只在书里看过。'},
{type:'say', who:'ynn',  text:'书里的海，永远是蓝的，永远有白色的浪。'},
{type:'say', who:'ynn',  text:'我一直想亲眼看看。'},
{type:'say', who:'me',   text:'那……为什么叫上我？'},
{type:'say', who:'narr', text:'她沉默了一会儿。海的声音在耳边一进一退。'},
{type:'say', who:'ynn',  text:'……你为什么会答应陪我出来？'},
{type:'say', who:'me',   text:'因为你说「一个人去没意思」。'},
{type:'say', who:'ynn',  text:'我确实这么说了。'},
{type:'say', who:'ynn',  text:'但那是三天前的事了。你还记得。'},
{type:'say', who:'me',   text:'你说的话，我一般都会记得。'},
{type:'say', who:'narr', text:'她愣了一下，转过头去看海。'},
{type:'say', who:'ynn',  text:'……海是灰色的。'},
{type:'say', who:'ynn',  text:'小时候我以为海是蓝色的，跟书里画的一样。'},
{type:'say', who:'ynn',  text:'后来才发现，天气不好的时候，它是灰的。'},
{type:'say', who:'me',   text:'今天是晴天啊。'},
{type:'say', who:'ynn',  text:'……那也许是我看错了。'},
{type:'say', who:'narr', text:'海风把她的头发吹到脸上，她没有去拨，只是任它挡着视线。'},
{type:'say', who:'me',   text:'（不是她看错。是她看到的，本来就和别人不一样。）'},
{type:'say', who:'me',   text:'（到这一刻，我才第一次觉得，她的「不太一样」，好像藏着什么事。）'},
{type:'choice', options:[
  {text:'「你带我来看的，是同一片海吧。」', aff:3, to:'ch5_a'},
  {text:'「下次天气好的时候，我们再来看一次。」', aff:5, to:'ch5_b'},
  {text:'「灰色也很好看。」', aff:2, to:'ch5_c'}
]},

{type:'label', name:'ch5_a'},
{type:'say', who:'me',   text:'「你带我来看的，是同一片海吧。」'},
{type:'say', who:'ynn',  text:'……嗯。是同一片。'},
{type:'say', who:'narr', text:'她终于把头发拨到耳后。'},
{type:'say', who:'ynn',  text:'那本书里的海，也是同一片。'},
{type:'say', who:'ynn',  text:'我小时候住的地方，也靠海。'},
{type:'say', who:'ynn',  text:'每天早上，我都能听见浪声醒来。'},
{type:'say', who:'me',   text:'那后来呢？'},
{type:'say', who:'ynn',  text:'……后来搬走了。'},
{type:'say', who:'ynn',  text:'搬到一个听不见海的地方。'},
{type:'say', who:'narr', text:'她笑了笑，那笑很淡，像被海风吹薄了一点。'},
{type:'jump', to:'ch5_end'},

{type:'label', name:'ch5_b'},
{type:'say', who:'me',   text:'「下次天气好的时候，我们再来看一次。」'},
{type:'say', who:'ynn',  text:'……下次。你这么快就约好了下次？'},
{type:'say', who:'me',   text:'嗯。因为我还没看够。'},
{type:'say', who:'narr', text:'海风忽然大了。她抬手按住被吹乱的头发，指尖有点抖。'},
{type:'say', who:'ynn',  text:'……你可真奇怪。'},
{type:'say', who:'me',   text:'哪里奇怪？'},
{type:'say', who:'ynn',  text:'一般的人，看完一次就不会再来了。'},
{type:'say', who:'ynn',  text:'尤其是我这种人。'},
{type:'say', who:'me',   text:'你这种人怎么了？'},
{type:'say', who:'ynn',  text:'……没什么。'},
{type:'say', who:'ynn',  text:'……好。那就下次。'},
{type:'say', who:'narr', text:'她说「下次」的时候，声音比海浪还轻。'},
{type:'jump', to:'ch5_end'},

{type:'label', name:'ch5_c'},
{type:'say', who:'me',   text:'「灰色也很好看。」'},
{type:'say', who:'ynn',  text:'……你为什么总是这样。'},
{type:'say', who:'me',   text:'哪样？'},
{type:'say', who:'ynn',  text:'把我说得很奇怪的东西，说成是好看的。'},
{type:'say', who:'narr', text:'她低下头，声音小得几乎被风盖住。'},
{type:'say', who:'ynn',  text:'……从来没有人这么说过。'},
{type:'say', who:'me',   text:'那就从我开始。'},
{type:'say', who:'ynn',  text:'……'},
{type:'say', who:'narr', text:'她没再说话，但肩膀慢慢放松下来。'},
{type:'jump', to:'ch5_end'},

{type:'label', name:'ch5_end'},
{type:'say', who:'narr', text:'天色慢慢暗下来。我们沿着海岸线往回走。'},
{type:'say', who:'ynn',  text:'海的声音，会一直响下去吧。'},
{type:'say', who:'me',   text:'嗯。一直都在。'},
{type:'say', who:'ynn',  text:'就算没有人听见，它也在响。'},
{type:'say', who:'narr', text:'她说这话的时候，望着远远的地方。'},
{type:'say', who:'narr', text:'我忽然觉得，她说的其实不是海。'},
{type:'say', who:'narr', text:'回程的巴士上，她靠着窗睡着了。'},
{type:'say', who:'narr', text:'车窗外，天色一点点暗下去，像被谁慢慢调低了亮度。'},
{type:'jump', to:'ch6'},

{type:'label', name:'ch6'},
{type:'chapter', title:'第 六 章', sub:'雨 天 的 伞'},
{type:'bg', cls:'bg-rain', fx:'rain'},
{type:'say', who:'narr', text:'梅雨季来得比预告早了一天。'},
{type:'say', who:'narr', text:'放学的时候，雨把整条街浇得发亮。'},
{type:'say', who:'narr', text:'我撑着伞站在校门口，看见她一个人站在屋檐下。'},
{type:'say', who:'narr', text:'别人都走了，只有她还在那里，像是在等雨停，又像是在等别的什么。'},
{type:'say', who:'me',   text:'没带伞？'},
{type:'say', who:'ynn',  text:'……忘在教室了。'},
{type:'say', who:'me',   text:'教室在三楼。要不要我上去帮你拿？'},
{type:'say', who:'ynn',  text:'不用。就几步路。'},
{type:'say', who:'me',   text:'几步路也是雨。'},
{type:'say', who:'ynn',  text:'……我不怕淋。'},
{type:'say', who:'me',   text:'走吧，我送你。'},
{type:'say', who:'ynn',  text:'伞太小了。'},
{type:'say', who:'me',   text:'那就一起淋一点。'},
{type:'say', who:'ynn',  text:'你会感冒的。'},
{type:'say', who:'me',   text:'那正好，明天可以请假。'},
{type:'say', who:'ynn',  text:'……你这人。'},
{type:'say', who:'narr', text:'她抿了抿嘴，最后还是一步跨进了伞下。'},
{type:'say', who:'narr', text:'我把伞偏过去，自己的右肩很快湿了一片。'},
{type:'say', who:'ynn',  text:'……你那边湿了。'},
{type:'say', who:'me',   text:'没事。'},
{type:'say', who:'ynn',  text:'过来一点。'},
{type:'say', who:'narr', text:'她抬手，把伞往我这边拨了拨。'},
{type:'say', who:'narr', text:'两个人之间的距离，忽然变得只有一把伞那么宽。'},
{type:'say', who:'narr', text:'雨点打在伞面上，声音很密，密得像有人在耳边说话。'},
{type:'say', who:'ynn',  text:'{name}。'},
{type:'say', who:'me',   text:'嗯？'},
{type:'say', who:'ynn',  text:'……这个城市，为什么看不见星星？'},
{type:'say', who:'me',   text:'因为灯太亮了。'},
{type:'say', who:'ynn',  text:'只是灯太亮吗？'},
{type:'say', who:'me',   text:'……还能因为什么？'},
{type:'say', who:'ynn',  text:'没什么。当我没问。'},
{type:'say', who:'narr', text:'她低下头，看雨水在地上汇成一条一条的小河。'},
{type:'say', who:'ynn',  text:'那如果我带你去一个没有灯的地方呢？'},
{type:'say', who:'narr', text:'她的声音混在雨里，我差点以为是错觉。'},
{type:'choice', options:[
  {text:'「那我就跟你去。」', aff:5, to:'ch6_a'},
  {text:'「你想去哪，我都陪你。」', aff:4, to:'ch6_b'},
  {text:'「先回家吧，雨太大了。」', aff:0, to:'ch6_c'}
]},

{type:'label', name:'ch6_a'},
{type:'say', who:'me',   text:'「那我就跟你去。」'},
{type:'say', who:'ynn',  text:'……不问是哪里？'},
{type:'say', who:'me',   text:'你带路就行。'},
{type:'say', who:'narr', text:'雨声里，她沉默了很久。'},
{type:'say', who:'ynn',  text:'你真的很轻信别人。'},
{type:'say', who:'me',   text:'只对你。'},
{type:'say', who:'narr', text:'她没有接话，但伞又往我这边挪了挪。'},
{type:'say', who:'ynn',  text:'……你说话，总是这样。'},
{type:'say', who:'me',   text:'哪样？'},
{type:'say', who:'ynn',  text:'让人没办法拒绝。'},
{type:'say', who:'narr', text:'我们一路没说别的。雨声替我们把话都说完了。'},
{type:'jump', to:'ch6_end'},

{type:'label', name:'ch6_b'},
{type:'say', who:'me',   text:'「你想去哪，我都陪你。」'},
{type:'say', who:'ynn',  text:'别随便说这种话。'},
{type:'say', who:'me',   text:'我是认真的。'},
{type:'say', who:'ynn',  text:'……那你可要说话算话。'},
{type:'say', who:'narr', text:'她的脚步慢了下来，像是舍不得走完这段路。'},
{type:'say', who:'ynn',  text:'以前有人也说过一样的话。'},
{type:'say', who:'me',   text:'后来呢？'},
{type:'say', who:'ynn',  text:'后来他走了。'},
{type:'say', who:'ynn',  text:'……所以你最好想清楚。'},
{type:'jump', to:'ch6_end'},

{type:'label', name:'ch6_c'},
{type:'say', who:'me',   text:'「先回家吧，雨太大了。」'},
{type:'say', who:'ynn',  text:'……嗯。'},
{type:'say', who:'narr', text:'她没再说话。伞外的雨，好像更大了。'},
{type:'say', who:'narr', text:'我心里有点后悔，却说不出为什么后悔。'},
{type:'jump', to:'ch6_end'},

{type:'label', name:'ch6_end'},
{type:'say', who:'narr', text:'把她送到家门口的时候，雨小了些。'},
{type:'say', who:'ynn',  text:'谢谢。……伞还你。'},
{type:'say', who:'me',   text:'你先留着。明天记得带来。'},
{type:'say', who:'ynn',  text:'……那明天呢？'},
{type:'say', who:'me',   text:'明天怎么了？'},
{type:'say', who:'ynn',  text:'明天要是不下雨呢。'},
{type:'say', who:'me',   text:'那就把伞放我桌上。'},
{type:'say', who:'ynn',  text:'……好。'},
{type:'say', who:'narr', text:'她转身进了门，没有回头。'},
{type:'say', who:'narr', text:'我站在原地，看着伞柄上她刚握过的地方。'},
{type:'say', who:'narr', text:'那片地方，还是温的。'},
{type:'jump', to:'ch7'},
{type:'label', name:'ch7'},
{type:'chapter', title:'第 七 章', sub:'文 化 祭 · 星 空 投 影'},
{type:'bg', cls:'bg-room', fx:''},
{type:'say', who:'narr', text:'文化祭前一周，我们开始布置教室。'},
{type:'say', who:'narr', text:'教室里堆满了纸、剪刀、胶带，还有一整盒用完的笔。'},
{type:'say', who:'narr', text:'她说要做一个「星空投影」。'},
{type:'say', who:'ynn',  text:'把纸剪成小孔，用手电筒照过去，天花板上就会有星星。'},
{type:'say', who:'me',   text:'这个我见过。'},
{type:'say', who:'ynn',  text:'嗯。但我做的是真的星星。'},
{type:'say', who:'me',   text:'真的？'},
{type:'say', who:'ynn',  text:'我查过资料。每颗星的亮度、距离，都不一样。'},
{type:'say', who:'ynn',  text:'只要孔的大小按比例来剪，就能还原出那片天空。'},
{type:'say', who:'me',   text:'那得剪多少个孔？'},
{type:'say', who:'ynn',  text:'我这里画了三千多个。'},
{type:'say', who:'me',   text:'三千多？'},
{type:'say', who:'ynn',  text:'这只是北半球冬天能看见的部分。'},
{type:'say', who:'ynn',  text:'还有夏天的，我还没来得及画。'},
{type:'say', who:'narr', text:'她说这些的时候，眼睛比平时亮。'},
{type:'say', who:'me',   text:'……你真的很喜欢星星。'},
{type:'say', who:'ynn',  text:'喜欢。因为星星不会骗人。'},
{type:'say', who:'ynn',  text:'它在那里，就是几万年前的样子。不管你看不看它。'},
{type:'say', who:'ynn',  text:'也不会因为你搬家，就消失。'},
{type:'say', who:'narr', text:'最后那句话，她说的很轻。'},
{type:'say', who:'narr', text:'我看着她低头剪孔的侧脸，忽然明白了什么。'},
{type:'choice', options:[
  {text:'「那你抬头的时候，我在你身边。」', aff:5, to:'ch7_a'},
  {text:'「我来帮你剪，一起做。」', aff:3, to:'ch7_b'},
  {text:'「别熬太晚，我陪你到做完。」', aff:2, to:'ch7_c'}
]},

{type:'label', name:'ch7_a'},
{type:'say', who:'me',   text:'「那你抬头的时候，我在你身边。」'},
{type:'say', who:'narr', text:'剪刀停住了。'},
{type:'say', who:'ynn',  text:'……你知道你在说什么吗。'},
{type:'say', who:'me',   text:'知道。'},
{type:'say', who:'ynn',  text:'也许你只是随口一说。'},
{type:'say', who:'me',   text:'我很少随口说这种话。'},
{type:'say', who:'narr', text:'她没抬头，只是把那张纸捏得更紧了些。'},
{type:'say', who:'ynn',  text:'……那就好。'},
{type:'say', who:'ynn',  text:'那我抬头的时候，你可别走。'},
{type:'say', who:'me',   text:'不走。'},
{type:'jump', to:'ch7_end'},

{type:'label', name:'ch7_b'},
{type:'say', who:'me',   text:'「我来帮你剪，一起做。」'},
{type:'say', who:'ynn',  text:'你会剪坏。'},
{type:'say', who:'me',   text:'剪坏了再重来。'},
{type:'say', who:'ynn',  text:'……那你坐这边。'},
{type:'say', who:'narr', text:'那把共用的小剪刀，在两个人手里传来传去。'},
{type:'say', who:'ynn',  text:'手要轻。'},
{type:'say', who:'ynn',  text:'剪太重，那颗星就太大了。'},
{type:'say', who:'me',   text:'这样？'},
{type:'say', who:'ynn',  text:'……太轻了。'},
{type:'say', who:'narr', text:'她伸手过来，覆在我手上，纠正了一下角度。'},
{type:'say', who:'narr', text:'然后又很快地收了回去，像是碰到了什么烫的东西。'},
{type:'say', who:'narr', text:'剪到后来，桌上的纸屑像下了一场小小的雪。'},
{type:'jump', to:'ch7_end'},

{type:'label', name:'ch7_c'},
{type:'say', who:'me',   text:'「别熬太晚，我陪你到做完。」'},
{type:'say', who:'ynn',  text:'不用。你先回去吧。'},
{type:'say', who:'me',   text:'我不走。'},
{type:'say', who:'ynn',  text:'你留在这里也帮不上忙。'},
{type:'say', who:'me',   text:'那就当我在旁边坐着。'},
{type:'say', who:'narr', text:'她看了我一眼，没再赶人。'},
{type:'say', who:'narr', text:'那天教室的灯，一直亮到很晚。'},
{type:'say', who:'narr', text:'她剪到一半，回头看了我三次。'},
{type:'say', who:'narr', text:'每次我都假装在看别的地方。'},
{type:'jump', to:'ch7_end'},

{type:'label', name:'ch7_end'},
{type:'say', who:'narr', text:'文化祭当天，我们的教室排起了长队。'},
{type:'bg', cls:'bg-star', fx:'stars'},
{type:'say', who:'narr', text:'灯一关，天花板上果然浮起了一整片星海。'},
{type:'say', who:'narr', text:'人群安静下来，只剩下一片轻轻的吸气声。'},
{type:'say', who:'ynn',  text:'……你看。这是她看不见的那片天空。'},
{type:'say', who:'me',   text:'谁看不见？'},
{type:'say', who:'ynn',  text:'……没什么。'},
{type:'say', who:'ynn',  text:'你看那颗最亮的。'},
{type:'say', who:'ynn',  text:'那是天狼星。'},
{type:'say', who:'ynn',  text:'几万年前它就这样亮着。'},
{type:'say', who:'ynn',  text:'我们现在看见的，其实是它的过去。'},
{type:'say', who:'me',   text:'那我们看见的，也是过去的自己？'},
{type:'say', who:'ynn',  text:'……也许。'},
{type:'say', who:'ynn',  text:'所以现在这一刻，要记住。'},
{type:'say', who:'narr', text:'她站在投影仪旁，被星光罩着。'},
{type:'say', who:'narr', text:'那一瞬间，我觉得她才是我要找的那颗星。'},
{type:'jump', to:'ch8'},

{type:'label', name:'ch8'},
{type:'chapter', title:'第 八 章', sub:'烟 火 大 会'},
{type:'bg', cls:'bg-fireworks', fx:''},
{type:'say', who:'narr', text:'夏末，镇上办了烟火大会。'},
{type:'say', who:'narr', text:'她穿了一件浅色的浴衣，站在人群里。'},
{type:'say', who:'narr', text:'我一眼就认出了她——因为整条街，只有她一个人在抬头看天。'},
{type:'say', who:'ynn',  text:'……你迟到了。'},
{type:'say', who:'me',   text:'路上堵。'},
{type:'say', who:'ynn',  text:'借口。'},
{type:'say', who:'me',   text:'真的是堵。'},
{type:'say', who:'ynn',  text:'堵车的话，你跑过来不就行了。'},
{type:'say', who:'me',   text:'穿浴衣的人，说话都这么理直气壮吗。'},
{type:'say', who:'ynn',  text:'……谁穿浴衣了。'},
{type:'say', who:'narr', text:'她嘴上说着，却把手里的苹果糖递给我一半。'},
{type:'say', who:'me',   text:'给我的？'},
{type:'say', who:'ynn',  text:'太甜了，我吃不完。'},
{type:'say', who:'me',   text:'那你为什么买一整颗？'},
{type:'say', who:'ynn',  text:'……因为看着好看。'},
{type:'say', who:'narr', text:'摊主在喊，人群在挤，我们站在中间，谁也没往前走。'},
{type:'say', who:'narr', text:'焰火在头顶炸开的时候，整条街都亮了。'},
{type:'bg', cls:'bg-fireworks', fx:'stars'},
{type:'say', who:'narr', text:'一朵接一朵，把夜空烧成了金色和白色。'},
{type:'say', who:'narr', text:'每一次炸开，她的脸都被照得很亮。'},
{type:'say', who:'ynn',  text:'{name}。你许愿了吗？'},
{type:'say', who:'me',   text:'现在许来得及吗？'},
{type:'say', who:'ynn',  text:'……来得及。'},
{type:'say', who:'narr', text:'我闭上眼睛。'},
{type:'say', who:'me',   text:'（希望明年这个时候，她还站在我旁边。）'},
{type:'say', who:'narr', text:'睁开眼的时候，她正看着我。'},
{type:'say', who:'ynn',  text:'……许了什么？'},
{type:'say', who:'me',   text:'说出来就不灵了。'},
{type:'say', who:'ynn',  text:'那我不问了。'},
{type:'say', who:'ynn',  text:'不过，我也许了一个。'},
{type:'say', who:'me',   text:'什么？'},
{type:'say', who:'ynn',  text:'不能告诉你。'},
{type:'say', who:'narr', text:'她转回头，看着最后一朵烟火散尽。'},
{type:'choice', options:[
  {text:'牵住她的手', aff:6, to:'ch8_a'},
  {text:'「明年，还一起来吧。」', aff:4, to:'ch8_b'},
  {text:'什么也没做，安静看烟火', aff:1, to:'ch8_c'}
]},

{type:'label', name:'ch8_a'},
{type:'say', who:'narr', text:'我伸出手，握住了她的。'},
{type:'say', who:'narr', text:'她的手很凉。'},
{type:'say', who:'ynn',  text:'……'},
{type:'say', who:'me',   text:'人群太挤了。'},
{type:'say', who:'ynn',  text:'……嗯。'},
{type:'say', who:'narr', text:'她没有抽开，反而轻轻地回握了一下。'},
{type:'say', who:'ynn',  text:'你的手，倒是挺暖的。'},
{type:'say', who:'me',   text:'那你多握一会儿。'},
{type:'say', who:'ynn',  text:'……就一会儿。'},
{type:'say', who:'narr', text:'那一刻，头顶的烟火声都好像退远了。'},
{type:'jump', to:'ch8_end'},

{type:'label', name:'ch8_b'},
{type:'say', who:'me',   text:'「明年，还一起来吧。」'},
{type:'say', who:'ynn',  text:'……你怎么总说「下次」、「明年」。'},
{type:'say', who:'me',   text:'因为我怕没有。'},
{type:'say', who:'ynn',  text:'怕什么？'},
{type:'say', who:'me',   text:'怕有一年，你就不在了。'},
{type:'say', who:'narr', text:'她沉默了一下。'},
{type:'say', who:'ynn',  text:'……那就明年。'},
{type:'say', who:'ynn',  text:'但如果我不在，你也要来。'},
{type:'say', who:'me',   text:'为什么？'},
{type:'say', who:'ynn',  text:'因为烟火会等你。'},
{type:'say', who:'narr', text:'她说这话的时候，眼睛比烟火还亮。'},
{type:'jump', to:'ch8_end'},

{type:'label', name:'ch8_c'},
{type:'say', who:'narr', text:'我什么都没说。'},
{type:'say', who:'narr', text:'最后一朵烟火散成一地金色的灰。'},
{type:'say', who:'ynn',  text:'……回去了。'},
{type:'say', who:'narr', text:'她走在我前面半步，始终没有回头。'},
{type:'say', who:'narr', text:'我跟在后面，看着她被路灯拉长的影子。'},
{type:'say', who:'narr', text:'那影子离我只有一步，却好像隔着一整个夏天。'},
{type:'jump', to:'ch8_end'},

{type:'label', name:'ch8_end'},
{type:'say', who:'narr', text:'回程的路上，两个人之间隔着一段刚好的距离。'},
{type:'say', who:'ynn',  text:'今夜的星星，好像比平时多。'},
{type:'say', who:'me',   text:'大概是被烟火点亮的。'},
{type:'say', who:'ynn',  text:'不。烟火只会遮住星星。'},
{type:'say', who:'ynn',  text:'能看见的，是因为你愿意抬头。'},
{type:'say', who:'narr', text:'那段距离，也许是两步，也许是一整个夏天。'},
{type:'jump', to:'ch9'},
{type:'label', name:'ch9'},
{type:'chapter', title:'第 九 章', sub:'天 台 的 夜'},
{type:'bg', cls:'bg-night', fx:'stars'},
{type:'say', who:'narr', text:'秋天，她约我到教学楼的天台。'},
{type:'say', who:'narr', text:'没有灯的地方，天空是深蓝色的。'},
{type:'say', who:'narr', text:'她说这是她找了很久才找到的地方。'},
{type:'say', who:'ynn',  text:'你看，这里有星星。'},
{type:'say', who:'me',   text:'……真的。'},
{type:'say', who:'me',   text:'我还以为这个城市里，一颗都看不见。'},
{type:'say', who:'ynn',  text:'看得见的。只是要在对的地方。'},
{type:'say', who:'ynn',  text:'我一直想找的地方。'},
{type:'say', who:'ynn',  text:'现在找到了，却不知道该跟谁说。'},
{type:'say', who:'me',   text:'所以叫我来了。'},
{type:'say', who:'ynn',  text:'嗯。'},
{type:'say', who:'me',   text:'为什么是我？'},
{type:'say', who:'ynn',  text:'……因为你是唯一一个，会认真听我说话的人。'},
{type:'say', who:'narr', text:'风从楼顶吹过，带着一点凉。'},
{type:'say', who:'ynn',  text:'{name}。我小时候，住在很远的地方。'},
{type:'say', who:'ynn',  text:'那里没有这么多灯，晚上抬头，全是星星。'},
{type:'say', who:'ynn',  text:'那时候我以为，全世界的人都看得见。'},
{type:'say', who:'ynn',  text:'后来搬家了。搬到了这里。'},
{type:'say', who:'ynn',  text:'然后有一天，我发现——我看不见星星了。'},
{type:'say', who:'me',   text:'……是不是因为这里的灯太亮？'},
{type:'say', who:'ynn',  text:'一开始我也这么想。'},
{type:'say', who:'ynn',  text:'所以我戒掉了晚上出门，整天待在屋子里。'},
{type:'say', who:'ynn',  text:'可是后来，连书上的字，我都快看不清了。'},
{type:'say', who:'narr', text:'她停了很久。'},
{type:'say', who:'ynn',  text:'不是星星没了。是我的眼睛。'},
{type:'say', who:'ynn',  text:'医生说是遗传，会一点一点暗下去。'},
{type:'say', who:'ynn',  text:'没有药，也没有办法。'},
{type:'say', who:'ynn',  text:'总有一天，我看什么都只剩下轮廓。'},
{type:'say', who:'narr', text:'风忽然停了。'},
{type:'say', who:'me',   text:'……所以你才做星空投影。'},
{type:'say', who:'ynn',  text:'嗯。我想在还记得的时候，把星星的样子留下来。'},
{type:'say', who:'ynn',  text:'留在纸上，留在教室里，留在——'},
{type:'say', who:'ynn',  text:'……留在你眼睛里。'},
{type:'say', who:'narr', text:'她终于转过来看着我。'},
{type:'say', who:'narr', text:'那是第一次，她让光线正面落在自己脸上。'},
{type:'say', who:'narr', text:'我这才发现，她一直在害怕——'},
{type:'say', who:'narr', text:'不是怕黑，是怕被人看见。'},
{type:'choice', options:[
  {text:'「那我就是你的星星。」', aff:8, to:'ch9_a'},
  {text:'「你看不见，我就替你看。」', aff:6, to:'ch9_b'},
  {text:'说不出话，只是握住她的手', aff:4, to:'ch9_c'}
]},

{type:'label', name:'ch9_a'},
{type:'say', who:'me',   text:'「那我就是你的星星。」'},
{type:'say', who:'ynn',  text:'……你算什么星星。'},
{type:'say', who:'me',   text:'一颗会说话、会陪你吃饭、会记得你所有话的星星。'},
{type:'say', who:'ynn',  text:'星星不会说话。'},
{type:'say', who:'me',   text:'那我这是限量版。'},
{type:'say', who:'narr', text:'她笑了。'},
{type:'say', who:'narr', text:'那是这一整年里，我第一次看见她真正笑起来。'},
{type:'say', who:'ynn',  text:'……好。那我就把你，记很久很久。'},
{type:'say', who:'ynn',  text:'比星星还久。'},
{type:'jump', to:'ch9_end'},

{type:'label', name:'ch9_b'},
{type:'say', who:'me',   text:'「你看不见，我就替你看。」'},
{type:'say', who:'ynn',  text:'……你能替我看多久？'},
{type:'say', who:'me',   text:'一辈子。'},
{type:'say', who:'ynn',  text:'别说一辈子。太长，我怕你做不到。'},
{type:'say', who:'me',   text:'那就从现在开始。'},
{type:'say', who:'ynn',  text:'现在？'},
{type:'say', who:'me',   text:'抬起头。那颗最亮的，我念给你听。'},
{type:'say', who:'narr', text:'她犹豫了一下，慢慢抬起头。'},
{type:'say', who:'narr', text:'她看了很久。'},
{type:'say', who:'ynn',  text:'……我看见了。'},
{type:'say', who:'narr', text:'她没有回答我别的问题，但肩膀轻轻靠了过来。'},
{type:'jump', to:'ch9_end'},

{type:'label', name:'ch9_c'},
{type:'say', who:'narr', text:'我没有说话。'},
{type:'say', who:'narr', text:'我只是伸出手，握住了她。'},
{type:'say', who:'narr', text:'她的手这次没有凉。'},
{type:'say', who:'ynn',  text:'……你不说话。'},
{type:'say', who:'ynn',  text:'但我好像听见了。'},
{type:'say', who:'me',   text:'听见了什么？'},
{type:'say', who:'ynn',  text:'……你心里在说的那句。'},
{type:'say', who:'narr', text:'我们就这样，站了很久。'},
{type:'jump', to:'ch9_end'},

{type:'label', name:'ch9_end'},
{type:'say', who:'narr', text:'那一夜之后，很多事情都变得不一样了。'},
{type:'say', who:'ynn',  text:'{name}，谢谢你。'},
{type:'say', who:'me',   text:'谢什么？'},
{type:'say', who:'ynn',  text:'谢谢你没有说「没关系」。'},
{type:'say', who:'ynn',  text:'……因为我知道，那是有关系的。'},
{type:'say', who:'narr', text:'至少，对我来说是这样。'},
{type:'jump', to:'ch10'},

{type:'label', name:'ch10'},
{type:'chapter', title:'终 章', sub:'最 后 的 星 空'},
{type:'bg', cls:'bg-morning', fx:''},
{type:'say', who:'narr', text:'冬天来了。她的视力，比秋天更差了一些。'},
{type:'say', who:'narr', text:'她开始上课坐得离黑板很近，开始把书举得很高。'},
{type:'say', who:'ynn',  text:'……别用那种眼神看我。'},
{type:'say', who:'me',   text:'我什么眼神。'},
{type:'say', who:'ynn',  text:'心疼的眼神。我还没瞎。'},
{type:'say', who:'narr', text:'她笑着说的。我却笑不出来。'},
{type:'bg', cls:'bg-snow', fx:''},
{type:'say', who:'narr', text:'下第一场雪的那天，她约我到天台。'},
{type:'say', who:'ynn',  text:'医生说了，再过半年，我可能什么都看不见了。'},
{type:'say', who:'ynn',  text:'所以在那之前，我想带你看一次真正的星空。'},
{type:'say', who:'ynn',  text:'不是投影的，不是画的。是真的。在星见丘的冬天。'},
{type:'say', who:'narr', text:'她说的那个地方，要坐很久的车，还要爬一段山路。'},
{type:'say', who:'narr', text:'那天夜里，我们出发了。'},
{type:'bg', cls:'bg-star', fx:'stars'},
{type:'say', who:'narr', text:'山顶。凌晨。'},
{type:'say', who:'narr', text:'天空像被谁泼翻了一整瓶墨水，又洒满了碎钻。'},
{type:'say', who:'ynn',  text:'……到了。你看，这就是我说的那片星空。'},
{type:'say', who:'ynn',  text:'跟我小时候看到的一模一样。'},
{type:'say', who:'narr', text:'她仰着头，眼睛一眨不眨，像是在拼命地记住。'},
{type:'say', who:'ynn',  text:'{name}。'},
{type:'say', who:'ynn',  text:'如果有一天，我真的什么都看不见了。'},
{type:'say', who:'ynn',  text:'你能不能，帮我把这片星空讲给我听。'},
{type:'say', who:'narr', text:'风很大。她的声音却很稳。'},
{type:'say', who:'narr', text:'我看着她。'},
{type:'say', who:'narr', text:'这一年来所有的画面，像走马灯一样从眼前掠过。'},
{type:'say', who:'narr', text:'迷路的走廊、图书馆的书、雨天的伞、投影的星光。'},
{type:'say', who:'narr', text:'还有此刻，站在我面前的她。'},
{type:'say', who:'narr', text:'我想说的话有很多。但我知道，只有一个答案是对的。'},
{type:'say', who:'narr', text:'——说出口。'},
{type:'jump', to:'final'},

{type:'label', name:'final'},
{type:'check', branches:[
  {min:36, to:'end_perfect'},
  {min:30, to:'end_fate'},
  {min:24, to:'end_true'},
  {min:17, to:'end_warm'},
  {min:10, to:'end_friend'},
  {min:4,  to:'end_miss'},
  {min:-99,to:'end_lonely'}
]},
{type:'label', name:'end_fate'},
{type:'bg', cls:'bg-garden', fx:''},
{type:'say', who:'narr', text:'我看着她，忽然想起图书馆那天。'},
{type:'say', who:'narr', text:'她说过：「星星不会骗人，它在那里，就是几万年前的样子。」'},
{type:'say', who:'me',   text:'「其实，你早就把答案留在这里了。」'},
{type:'say', who:'ynn',  text:'……什么答案？'},
{type:'say', who:'me',   text:'「你只是嘴上说不要，可你一直在等一个人，陪你抬头。」'},
{type:'say', who:'me',   text:'「那个人，从今天起，就是我。」'},
{type:'say', who:'narr', text:'她笑了。那是一种被人看穿之后，终于放下心的笑。'},
{type:'say', who:'ynn',  text:'……你怎么知道。'},
{type:'say', who:'me',   text:'因为我也在等。'},
{type:'say', who:'ynn',  text:'{name}。'},
{type:'say', who:'ynn',  text:'你抬头的时候，我陪你。'},
{type:'say', who:'ynn',  text:'你低头的时候，我也在。'},
{type:'end', kind:'F A T E   E N D', title:'一起抬头的人',
  text:'你们没有轰轰烈烈的告白，只有一句心照不宣的约定。\n从那个冬天起，星见丘的天台成了你们的地方。\n就算她终将看不见星星，\n她也知道，身边有一盏永远为她亮着的灯。',
  affText:'好 感 度 ：'},

{type:'label', name:'end_perfect'},
{type:'bg', cls:'bg-star', fx:'stars'},
{type:'say', who:'me',   text:'「不用我讲给你听。」'},
{type:'say', who:'ynn',  text:'……？'},
{type:'say', who:'me',   text:'因为从今天起，我会一直在你旁边。'},
{type:'say', who:'me',   text:'你抬头的时候，我就在。'},
{type:'say', who:'me',   text:'你看不见了，我就把整片天空，说成话，讲给你听。'},
{type:'say', who:'me',   text:'一直讲到，我们都老得看不清为止。'},
{type:'say', who:'narr', text:'她愣了很久。然后，眼泪掉了下来。'},
{type:'say', who:'ynn',  text:'……你这个人，真的很讨厌。'},
{type:'say', who:'ynn',  text:'你知道我等这句话，等了多久吗。'},
{type:'say', who:'narr', text:'她扑进我怀里。雪、星光、风，都在那一刻静止了。'},
{type:'say', who:'ynn',  text:'{name}。……我喜欢你。'},
{type:'say', who:'me',   text:'我也是。'},
{type:'say', who:'narr', text:'那一刻，我终于明白。'},
{type:'say', who:'narr', text:'她一直在找的，从来不是星空。'},
{type:'say', who:'narr', text:'是那个愿意陪她看星空的人。'},
{type:'end', kind:'T R U E   E N D', title:'与你共度的四季',
  text:'那一夜之后，我们再也没有分开过。\n她的世界一点点暗下来，她身边的光却越来越多。\n多年以后，她在夜里握紧我的手，笑着说：\n「我虽然看不见，但我一直都知道——你在。」',
  affText:'好 感 度 ：'},

{type:'label', name:'end_true'},
{type:'bg', cls:'bg-star', fx:'stars'},
{type:'say', who:'me',   text:'「可以。我讲给你听。」'},
{type:'say', who:'me',   text:'「但我有一个条件。」'},
{type:'say', who:'ynn',  text:'……什么条件？'},
{type:'say', who:'me',   text:'「你要让我，一直待在你身边。」'},
{type:'say', who:'narr', text:'她没有立刻回答。'},
{type:'say', who:'narr', text:'但很久之后，她轻轻点了点头。'},
{type:'say', who:'ynn',  text:'……好。那你可要记得，你答应过我。'},
{type:'say', who:'narr', text:'那一夜，我们并肩坐着看完整片星空。'},
{type:'end', kind:'G O O D   E N D', title:'答应过的话',
  text:'她最终没能留住视力，却留住了你。\n很多年以后，她在黑暗里准确无误地摸到你的手。\n「你看，」她说，「你把星星都讲给我听了。」',
  affText:'好 感 度 ：'},

{type:'label', name:'end_warm'},
{type:'bg', cls:'bg-star', fx:'stars'},
{type:'say', who:'narr', text:'我说了一些话。是真心话，但说得不够好。'},
{type:'say', who:'narr', text:'她听完，安静地笑了。'},
{type:'say', who:'ynn',  text:'……谢谢你。'},
{type:'say', who:'ynn',  text:'虽然还不是我想要的答案。'},
{type:'say', who:'me',   text:'那我该说什么？'},
{type:'say', who:'ynn',  text:'……你自己想。'},
{type:'say', who:'narr', text:'那天我们回来了。关系没变，也没说破。'},
{type:'end', kind:'W A R M   E N D', title:'再靠近一点',
  text:'你们成了彼此最重要的人，却谁也没先开口。\n很多年后你会想：\n如果那天，再多说一句话，是不是就不一样了？\n——不过没关系，她一直在你身边。',
  affText:'好 感 度 ：'},

{type:'label', name:'end_friend'},
{type:'bg', cls:'bg-snow', fx:''},
{type:'say', who:'narr', text:'我说了。但她说，谢谢，然后摇了摇头。'},
{type:'say', who:'ynn',  text:'你很好。但我们，还是先做朋友吧。'},
{type:'say', who:'me',   text:'……为什么。'},
{type:'say', who:'ynn',  text:'因为我怕。'},
{type:'say', who:'ynn',  text:'我怕有一天，我连你的脸都记不清了。'},
{type:'say', who:'ynn',  text:'那时候，你还会喜欢我吗？'},
{type:'say', who:'narr', text:'我没有回答。因为我也不知道。'},
{type:'end', kind:'F R I E N D   E N D', title:'守着距离',
  text:'你们还是每天一起吃饭、一起走回家。\n只是有些话，谁都没有再提。\n很多年过去，你依然记得那晚的雪。\n还有她说的那句：「你很好。」',
  affText:'好 感 度 ：'},

{type:'label', name:'end_miss'},
{type:'bg', cls:'bg-night', fx:'stars'},
{type:'say', who:'narr', text:'我张了张嘴，可是什么也没说出来。'},
{type:'say', who:'narr', text:'风太大，把那句话吹散了。'},
{type:'say', who:'ynn',  text:'……你在说什么？'},
{type:'say', who:'me',   text:'……没什么。'},
{type:'say', who:'ynn',  text:'哦。'},
{type:'say', who:'narr', text:'她转回去，继续抬头看星星。'},
{type:'say', who:'narr', text:'那一夜，我们谁也没有再说话。'},
{type:'end', kind:'M I S S   E N D', title:'没说出口的话',
  text:'后来她转学了。\n你偶尔会在夜里抬头，想起星见丘的那片山顶。\n那句话，你终究没来得及说。\n——如果当时，再勇敢一点就好了。',
  affText:'好 感 度 ：'},

{type:'label', name:'end_lonely'},
{type:'bg', cls:'bg-night', fx:''},
{type:'say', who:'ynn',  text:'……你什么都不想说吗。'},
{type:'say', who:'narr', text:'我摇了摇头。'},
{type:'say', who:'ynn',  text:'我明白了。'},
{type:'say', who:'narr', text:'她把手插进口袋，转身往山下走。'},
{type:'say', who:'narr', text:'她的背影越来越小，最后消失在夜色里。'},
{type:'say', who:'narr', text:'我站在原地，看着那片星空。'},
{type:'say', who:'narr', text:'星星还在那里。只是没有人再仰头看它了。'},
{type:'end', kind:'L O N E L Y   E N D', title:'一个人的星空',
  text:'那晚之后，她再没约过你。\n教室里那个星空投影，也被拆了下来。\n多年过去，你才明白：\n有些星星，错过了就再也看不见了。',
  affText:'好 感 度 ：'}
];
