/* 剧本文件：{name} 会替换成男主名字。type: chapter/bg/say/choice/label/jump/check/end */
const SCRIPT = [
{type:'chapter',title:'序 章',sub:'四 月 · 樱 色 的 坡 道'},
{type:'bg',cls:'bg-day',fx:''},
{type:'say',who:'narr',text:'四月，樱花开满了星见丘的坡道。\n花瓣被风卷起来，像是有人把整片天空撕成了碎片。'},
{type:'say',who:'narr',text:'我——刚转学来的二年级生，正拎着书包站在校门口发呆。'},
{type:'say',who:'me',text:'（这就是我接下来两年要待的地方啊……）'},
{type:'say',who:'narr',text:'校舍比地图上画的还要大。走廊弯弯绕绕，像是故意和新生作对。'},
{type:'say',who:'me',text:'……我迷路了。'},
{type:'say',who:'narr',text:'在第三次经过同一个消防栓之后，我终于承认了这个事实。'},
{type:'say',who:'me',text:'（离上课还有五分钟。教室是二年B组……在几楼来着？）'},
{type:'say',who:'narr',text:'就在我准备原地放弃的时候，走廊尽头传来一个声音。'},
{type:'say',who:'ynn',text:'你在找二年B组吧。'},
{type:'say',who:'narr',text:'靠着窗边站着一个女生。逆光里看不清表情，只看见她抱着很厚的一本书。'},
{type:'say',who:'ynn',text:'从刚才开始，你已经在楼梯口转了三圈。'},
{type:'say',who:'me',text:'你、你一直在看？'},
{type:'say',who:'ynn',text:'我只是刚好在等人。顺便看了三圈。'},
{type:'say',who:'ynn',text:'二年B组在三楼东侧。直走，右拐，经过两个教室，左手边。'},
{type:'say',who:'narr',text:'她的语气没什么起伏，句子却像刻在纸上的标尺一样准确。'},
{type:'say',who:'me',text:'谢……'},
{type:'say',who:'ynn',text:'还有两分钟。跑的话，来得及。'},
{type:'say',who:'narr',text:'说完，她低下头重新翻开书——封面上写着两个字：《海》。'},
{type:'say',who:'narr',text:'我记住了她的侧脸，然后真的跑了起来。'},

{type:'chapter',title:'第 一 章',sub:'走 廊 尽 头 的 她'},
{type:'bg',cls:'bg-day',fx:''},
{type:'say',who:'narr',text:'结果当然没赶上。第一节课，我在讲台边站了十分钟。'},
{type:'say',who:'narr',text:'午休，我在自动贩卖机前排队，又看见了那个抱着书的女生。'},
{type:'say',who:'ynn',text:'……迷路的人。'},
{type:'say',who:'me',text:'我叫{name}。不叫迷路的人。'},
{type:'say',who:'ynn',text:'ynn。请多指教，迷路的人。'},
{type:'say',who:'me',text:'（完全没打算改口。）'},
{type:'choice',options:[
  {text:'「昨天多谢了，真的帮了大忙。」',aff:1,to:'ch1_a'},
  {text:'「我请你喝瓶牛奶，当谢礼。」',aff:3,to:'ch1_b'},
  {text:'「你该不会天天守在这儿看新生出丑吧？」',aff:-1,to:'ch1_c'}
]},

{type:'label',name:'ch1_a'},
{type:'say',who:'me',text:'「昨天多谢了，真的帮了大忙。」'},
{type:'say',who:'ynn',text:'……没什么。'},
{type:'say',who:'narr',text:'她的耳朵好像红了一下。不过也可能是阳光的关系。'},
{type:'say',who:'ynn',text:'我只是不喜欢看见有人在走廊上原地打转。'},
{type:'say',who:'me',text:'这算哪门子的理由啊。'},
{type:'say',who:'ynn',text:'很好的理由。'},
{type:'say',who:'narr',text:'她把书合上，抱着往教室走。走了两步，又停下。'},
{type:'say',who:'ynn',text:'{name}。'},
{type:'say',who:'me',text:'嗯？'},
{type:'say',who:'ynn',text:'下午第二节课要换教室。别又迷路。'},
{type:'say',who:'narr',text:'她说完就走了。我在原地站了几秒，忽然觉得这个学校也不错。'},
{type:'jump',to:'ch1_end'},

{type:'label',name:'ch1_b'},
{type:'say',who:'me',text:'「我请你喝瓶牛奶，当谢礼。」'},
{type:'say',who:'narr',text:'她看了我一眼，看了看贩卖机，又看了我一眼。'},
{type:'say',who:'ynn',text:'……草莓的。'},
{type:'say',who:'me',text:'诶？'},
{type:'say',who:'ynn',text:'草莓味。三号按钮。'},
{type:'say',who:'narr',text:'我买了瓶草莓牛奶递过去。她双手接住，像捧着一件很重要的东西。'},
{type:'say',who:'ynn',text:'谢谢。'},
{type:'say',who:'narr',text:'她把牛奶贴在脸颊上，眯了眯眼。'},
{type:'say',who:'ynn',text:'……凉的，很舒服。'},
{type:'say',who:'me',text:'你笑了。'},
{type:'say',who:'ynn',text:'没有。'},
{type:'say',who:'me',text:'笑了。'},
{type:'say',who:'ynn',text:'……没有。'},
{type:'say',who:'narr',text:'她转身就走，比昨天走得快。但我发誓，她嘴角还是翘着的。'},
{type:'jump',to:'ch1_end'},

{type:'label',name:'ch1_c'},
{type:'say',who:'me',text:'「你该不会天天守在这儿看新生出丑吧？」'},
{type:'say',who:'narr',text:'空气安静了三秒。'},
{type:'say',who:'ynn',text:'……原来你是这么想的。'},
{type:'say',who:'me',text:'呃，我开玩笑的。'},
{type:'say',who:'ynn',text:'我知道。只是玩笑不好笑。'},
{type:'say',who:'narr',text:'她把书抱得更紧了一点，转身走了。'},
{type:'say',who:'narr',text:'我站在原地，看着她的背影，忽然觉得自己刚才很蠢。'},
{type:'say',who:'me',text:'（下次……还是好好说话吧。）'},
{type:'jump',to:'ch1_end'},

{type:'label',name:'ch1_end'},
{type:'say',who:'narr',text:'那天下午，我在楼梯口又遇到了她。她什么都没说，只抬了抬下巴，指了个方向。'},
{type:'say',who:'me',text:'……谢了。'},
{type:'say',who:'ynn',text:'嗯。'},
{type:'say',who:'narr',text:'她走在我前面半步，像是怕我跟丢。夕阳把两个人的影子拉得很长。'},

{type:'chapter',title:'第 二 章',sub:'雨 · 与 一 把 伞'},
{type:'bg',cls:'bg-rain',fx:'rain'},
{type:'say',who:'narr',text:'梅雨季来得毫无预告。放学时，天已经黑得像晚上七点。'},
{type:'say',who:'narr',text:'我站在玄关，看着外面的雨帘，感叹自己没有带伞这件事。'},
{type:'say',who:'me',text:'（走回去大概二十分钟……冲吧。）'},
{type:'say',who:'ynn',text:'你要淋雨回去？'},
{type:'say',who:'narr',text:'ynn站在我旁边，手里是一把透明的伞。伞柄上挂着一只很旧的小熊挂件。'},
{type:'say',who:'me',text:'你家不是反方向吗？'},
{type:'say',who:'ynn',text:'绕一圈而已。'},
{type:'say',who:'ynn',text:'……一起走吧。'},
{type:'choice',options:[
  {text:'「伞往你那边多挪一点，你肩膀都湿了。」',aff:3,to:'ch2_a'},
  {text:'「那一起跑吧，反正都湿透了。」',aff:1,to:'ch2_b'},
  {text:'「你先走吧，我自己能回去。」',aff:-2,to:'ch2_c'}
]},

{type:'label',name:'ch2_a'},
{type:'say',who:'me',text:'「伞往你那边多挪一点，你肩膀都湿了。」'},
{type:'say',who:'ynn',text:'……那你呢。'},
{type:'say',who:'me',text:'我皮实。'},
{type:'say',who:'narr',text:'她沉默了一会儿，把伞又往我这边推了回来。'},
{type:'say',who:'ynn',text:'两个人一起湿，不如一个人湿。这叫效率。'},
{type:'say',who:'me',text:'这是哪门子的效率啊。'},
{type:'say',who:'ynn',text:'……我的效率。'},
{type:'say',who:'narr',text:'结果那把伞在两个人之间来回推了好几次，最后谁都没淋到多少雨。'},
{type:'say',who:'narr',text:'倒是肩膀，一直贴着肩膀。'},
{type:'jump',to:'ch2_end'},

{type:'label',name:'ch2_b'},
{type:'say',who:'me',text:'「那一起跑吧，反正都湿透了。」'},
{type:'say',who:'ynn',text:'……幼稚。'},
{type:'say',who:'narr',text:'但她还是把伞收了一半，跟上了我的脚步。'},
{type:'say',who:'narr',text:'水花在脚下溅开，两个人的笑声混进了雨声里。'},
{type:'say',who:'ynn',text:'{name}，你跑得真慢。'},
{type:'say',who:'me',text:'你刚才明明说不跑的！'},
{type:'say',who:'ynn',text:'……我没说。'},
{type:'say',who:'narr',text:'那天回家我感冒了。第二天来学校，桌洞里多了一包感冒药。'},
{type:'say',who:'narr',text:'没有署名。'},
{type:'jump',to:'ch2_end'},

{type:'label',name:'ch2_c'},
{type:'say',who:'me',text:'「你先走吧，我自己能回去。」'},
{type:'say',who:'ynn',text:'……好。'},
{type:'say',who:'narr',text:'她走了两步，又回头看了一次。'},
{type:'say',who:'narr',text:'我把书包顶在头上，冲进雨里。'},
{type:'say',who:'narr',text:'跑到一半，我忽然觉得，刚才那句话好像说错了。'},
{type:'jump',to:'ch2_end'},

{type:'label',name:'ch2_end'},
{type:'say',who:'narr',text:'那条回家的路，因为多了一把伞，好像变短了。'},
{type:'say',who:'ynn',text:'明天……带伞。天气预报说还要下。'},
{type:'say',who:'me',text:'知道了，长官。'},
{type:'say',who:'ynn',text:'……谁是你的长官。'},
{type:'say',who:'narr',text:'她把透明伞收好，小熊挂件晃了晃。'},

{type:'chapter',title:'第 三 章',sub:'图 书 馆 的 午 后'},
{type:'bg',cls:'bg-indoor',fx:''},
{type:'say',who:'narr',text:'期中考前两周。我抱着三本参考书，在图书馆的角落找到了她。'},
{type:'say',who:'narr',text:'她坐在靠窗的位置，面前摊着笔记本，手里却在画着什么。'},
{type:'say',who:'me',text:'你也在复习？'},
{type:'say',who:'ynn',text:'嗯。'},
{type:'say',who:'narr',text:'她把笔记本往前挪了挪，挡住我的视线。太可疑了。'},
{type:'say',who:'narr',text:'阳光落在她手背上。铅笔在纸上沙沙地响。'},
{type:'choice',options:[
  {text:'「画得真好。是什么？」（认真地夸她）',aff:3,to:'ch3_a'},
  {text:'「让我看看你的笔记本？」（伸手去拿）',aff:-3,to:'ch3_b'},
  {text:'什么都不问，坐下来安静地陪她',aff:2,to:'ch3_c'}
]},

{type:'label',name:'ch3_a'},
{type:'say',who:'me',text:'「画得真好。是什么？」'},
{type:'say',who:'ynn',text:'……你不该看到的。'},
{type:'say',who:'me',text:'是星空？'},
{type:'say',who:'narr',text:'画纸上是一片深蓝。一颗一颗的星星，全是铅笔点出来的，密密麻麻。'},
{type:'say',who:'ynn',text:'……星见丘。这个城市，晚上看不见星星。所以只能画。'},
{type:'say',who:'me',text:'为什么是星星？'},
{type:'say',who:'ynn',text:'因为我小时候，在奶奶家看过一次。一整条银河，像撒下来的糖。'},
{type:'say',who:'ynn',text:'……我从那天开始，就想再看一次。'},
{type:'say',who:'narr',text:'她像是后悔说了这么多，把本子合上。'},
{type:'say',who:'ynn',text:'别多想。只是随便画画。'},
{type:'say',who:'me',text:'我没多想。我只是觉得……很好看。'},
{type:'say',who:'narr',text:'她的笔停了一下。'},
{type:'say',who:'ynn',text:'……嗯。'},
{type:'jump',to:'ch3_end'},

{type:'label',name:'ch3_b'},
{type:'say',who:'me',text:'「让我看看你的笔记本？」'},
{type:'say',who:'narr',text:'她按住了本子。'},
{type:'say',who:'ynn',text:'不行。'},
{type:'say',who:'me',text:'只是看一眼——'},
{type:'say',who:'ynn',text:'{name}。'},
{type:'say',who:'narr',text:'她抬起头，眼睛很认真。'},
{type:'say',who:'ynn',text:'我不想给你看。为什么你听不见呢。'},
{type:'say',who:'narr',text:'我伸出去的手僵在半空。'},
{type:'say',who:'narr',text:'图书馆很安静，安静得能听见自己刚才的失礼。'},
{type:'jump',to:'ch3_end'},

{type:'label',name:'ch3_c'},
{type:'say',who:'narr',text:'我什么也没问，把书包放下，坐在她对面。'},
{type:'say',who:'narr',text:'翻书，写题，偶尔抬头——她还在画她的星空。'},
{type:'say',who:'narr',text:'一个小时过去，她一句话没说。'},
{type:'say',who:'narr',text:'离开的时候，她忽然开口。'},
{type:'say',who:'ynn',text:'……你不问吗？'},
{type:'say',who:'me',text:'如果你想说的话，会说。'},
{type:'say',who:'narr',text:'她看了我很久，久到我以为她要说什么了。'},
{type:'say',who:'ynn',text:'……你这个人，还不错。'},
{type:'say',who:'narr',text:'那是她第二次这么说我。'},
{type:'jump',to:'ch3_end'},

{type:'label',name:'ch3_end'},
{type:'say',who:'narr',text:'从那天起，图书馆靠窗的位置，成了两个人的座位。'},

{type:'chapter',title:'第 四 章',sub:'文 化 祭 的 星 空'},
{type:'bg',cls:'bg-dusk',fx:''},
{type:'say',who:'narr',text:'文化祭前夜，班里决定做一台星空投影。'},
{type:'say',who:'narr',text:'原因很简单——有人说，「反正我们班有个会画星星的人」。'},
{type:'say',who:'narr',text:'于是那天晚上，美术教室里只剩下两个人。'},
{type:'say',who:'ynn',text:'这里，再补一点。不然北极星会掉下来。'},
{type:'say',who:'me',text:'星星还能掉下来吗？'},
{type:'say',who:'ynn',text:'能。只要画错了，就会。'},
{type:'say',who:'narr',text:'她踮起脚，在天花板的投影纸上补了一个小小的点。'},
{type:'say',who:'ynn',text:'好了。'},
{type:'say',who:'narr',text:'灯关掉的一瞬间，整个教室变成了一片夜。'},
{type:'say',who:'me',text:'哇……'},
{type:'say',who:'ynn',text:'……还行吧。'},
{type:'say',who:'narr',text:'她坐在课桌上，仰着头。星光落在她的眼睛里。'},
{type:'choice',options:[
  {text:'「明天，一起去天台看真正的星星吧。」',aff:4,to:'ch4_a'},
  {text:'「你看起来很开心。」',aff:2,to:'ch4_b'},
  {text:'「先回去睡吧，明天还要早起。」',aff:-2,to:'ch4_c'}
]},

{type:'label',name:'ch4_a'},
{type:'say',who:'me',text:'「明天，文化祭结束以后，一起去天台吧。」'},
{type:'say',who:'ynn',text:'天台？'},
{type:'say',who:'me',text:'我给你看真正的星星。虽然这个城市看不到什么。'},
{type:'say',who:'ynn',text:'……看不到的星星，要看什么？'},
{type:'say',who:'me',text:'看你画的那一片。'},
{type:'say',who:'me',text:'这样，说不定就看见了。'},
{type:'say',who:'narr',text:'她安静了很久。久到我以为自己说错了话。'},
{type:'say',who:'ynn',text:'……好。'},
{type:'say',who:'ynn',text:'七点。不要迟到。'},
{type:'say',who:'narr',text:'那是她第一次，答应我的邀请。'},
{type:'jump',to:'ch4_end'},

{type:'label',name:'ch4_b'},
{type:'say',who:'me',text:'「你看起来很开心。」'},
{type:'say',who:'ynn',text:'没有。'},
{type:'say',who:'me',text:'有。嘴角。'},
{type:'say',who:'ynn',text:'……那是画歪了。'},
{type:'say',who:'me',text:'画歪了会笑吗？'},
{type:'say',who:'ynn',text:'会。'},
{type:'say',who:'ynn',text:'……因为很开心。'},
{type:'say',who:'narr',text:'她小声说完最后四个字，把脸埋进膝盖里。'},
{type:'jump',to:'ch4_end'},

{type:'label',name:'ch4_c'},
{type:'say',who:'me',text:'「先回去睡吧，明天还要早起。」'},
{type:'say',who:'ynn',text:'……嗯。'},
{type:'say',who:'narr',text:'她站起来，把灯打开。教室里的星空一下子消失了。'},
{type:'say',who:'narr',text:'她收拾东西的动作很轻，像是怕吵醒什么。'},
{type:'say',who:'ynn',text:'晚安。'},
{type:'say',who:'narr',text:'走到门口，她停了一下。'},
{type:'say',who:'ynn',text:'{name}。'},
{type:'say',who:'me',text:'嗯？'},
{type:'say',who:'ynn',text:'……没事。晚安。'},
{type:'say',who:'narr',text:'门关上之后，投影纸还挂在那里。'},
{type:'say',who:'narr',text:'我忽然觉得，刚才那句话应该收回来。'},
{type:'jump',to:'ch4_end'},

{type:'label',name:'ch4_end'},
{type:'say',who:'narr',text:'那一夜，我翻来覆去。窗外真的看不见星星。'},

{type:'chapter',title:'终 章',sub:'天 台 上 的 星 空'},
{type:'bg',cls:'bg-star',fx:'stars'},
{type:'say',who:'narr',text:'文化祭的最后一天，烟花在远处响了三声。'},
{type:'say',who:'narr',text:'七点零二分。我推开天台的门——她已经在那里了。'},
{type:'say',who:'ynn',text:'你迟到了两分钟。'},
{type:'say',who:'me',text:'对不起。楼梯太黑。'},
{type:'say',who:'ynn',text:'嗯。'},
{type:'say',who:'narr',text:'夜风把她的头发吹起来。她抱着那本《海》，像抱着整个夏天。'},
{type:'say',who:'ynn',text:'你说要看星星。'},
{type:'say',who:'me',text:'是啊。'},
{type:'say',who:'ynn',text:'这里根本看不到星星。'},
{type:'say',who:'me',text:'我知道。'},
{type:'say',who:'narr',text:'我把手电筒关了。天台上只剩下城市的光。'},
{type:'say',who:'ynn',text:'……那你在看什么。'},
{type:'say',who:'me',text:'看你。'},
{type:'say',who:'narr',text:'她愣住了。'},
{type:'say',who:'ynn',text:'你说什么？'},
{type:'say',who:'me',text:'我说——'},
{type:'choice',options:[
  {text:'「ynn，我喜欢你。从你把伞推回来的那天起。」',aff:6,to:'final_yes'},
  {text:'「……没什么。我们回去吧。」',aff:0,to:'final_no'}
]},

{type:'label',name:'final_yes'},
{type:'say',who:'me',text:'「ynn，我喜欢你。」'},
{type:'say',who:'me',text:'「从你把那把伞推回来的那天起，我就一直在想这件事。」'},
{type:'say',who:'narr',text:'天台上很安静。远处又亮起一团烟花。'},
{type:'say',who:'ynn',text:'……你知道我为什么每天都抱着这本书吗？'},
{type:'say',who:'me',text:'不知道。'},
{type:'say',who:'ynn',text:'因为《海》的最后一页，画着一片星空。'},
{type:'say',who:'ynn',text:'那是我小时候看到的那一片。我一直在等，等有人愿意陪我去看第二次。'},
{type:'say',who:'narr',text:'她抬起头，眼睛里有从城市那头借来的光。'},
{type:'say',who:'ynn',text:'{name}。'},
{type:'say',who:'ynn',text:'……你来得有点晚。但是，来了。'},
{type:'check',branches:[
  {min:14,to:'end_true'},
  {min:8,to:'end_normal'},
  {min:-999,to:'end_normal'}
]},

{type:'label',name:'final_no'},
{type:'say',who:'me',text:'「……没什么。我们回去吧。」'},
{type:'say',who:'narr',text:'话出口的一瞬间，我看到她眼里的光晃了一下。'},
{type:'say',who:'ynn',text:'……嗯。回去吧。'},
{type:'say',who:'narr',text:'下楼梯的时候，她走在前面，一句话都没说。'},
{type:'say',who:'narr',text:'那把透明伞上，小熊挂件轻轻撞着栏杆。'},
{type:'check',branches:[
  {min:10,to:'end_friend'},
  {min:-999,to:'end_bad'}
]},

{type:'label',name:'end_true'},
{type:'end',kind:'TRUE END',title:'星见丘的一等星',affText:'好感度：',text:'「明年夏天，我的自行车后座，你坐不坐？」\n\n她说这句话的时候，脸朝着城市的方向，没看我。\n\n「坐。」\n\n「……那就说定了。」\n\n那天晚上，我们一直站到烟花全部熄灭。\n从那之后，我每个周末都骑车带她出城。\n\n去那个还有银河的地方。\n\n而星见丘——\n那个连星星都看不见的小城，\n在我们之间，亮起了一颗一等星。\n\n（第一章 · 完）'},

{type:'label',name:'end_normal'},
{type:'end',kind:'NORMAL END',title:'一颗星星的距离',affText:'好感度：',text:'「……我，需要一点时间。」\n\n她把书抱得很紧，像怕它被风吹走。\n\n「不是拒绝。只是——我还不太会。」\n\n「我会等的。」\n\n「嗯。那就，慢慢等吧。」\n\n那天之后，图书馆的座位还是两个。\n她还是会画星星，还是会说「没有」。\n\n只是偶尔，她会把笔记本往我这边挪一挪。\n\n只挪一点点。'},

{type:'label',name:'end_friend'},
{type:'end',kind:'FRIEND END',title:'未完的星图',affText:'好感度：',text:'「{name}。」\n\n走到校门口的时候，她忽然叫住我。\n\n「刚才在天台，你本来想说什么？」\n\n「……没什么。」\n\n「哦。」\n\n她点了点头，转身走进夜色里。\n\n走了几步，又回头。\n\n「那，等你想说的时候再说。」\n「我不会走太远的。」\n\n那年夏天就这样结束了。\n她画的那张星图，还差最后一颗星没画完。'},

{type:'label',name:'end_bad'},
{type:'end',kind:'BAD END',title:'擦肩而过的四月',affText:'好感度：',text:'那天以后，她还是会在走廊上遇到我。\n\n「早。」\n「早。」\n\n就这样。\n\n她还是抱着那本《海》，还是坐在图书馆靠窗的位置。\n只是那个位置上，再也没有第二个人的书包。\n\n文化祭的投影纸，被收进了仓库。\n\n我偶尔会想——\n\n如果那天，我把伞往她那边挪一点点；\n如果那天，我没有伸手去抢那本笔记本；\n如果那天，我说出口了。\n\n……但四月已经过去了。\n\n这个城市，还是看不见星星。'}
];
